name: "build"

on:
  push:
    branches:
      - jevinskie/main

  pull_request:

  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - env-alpine
          - env-android:jdk11
          - env-android:jdk15
          - env-android:jdk8
          - env-android:latest
          - env-archlinux
          - env-debian
          - env-fedora
          - env-opensuse
          - env-sphinx
          - env-ubuntu:14.04
          - env-ubuntu:16.04
          - env-ubuntu:18.04
          - env-ubuntu:20.04
          - env-ubuntu:22.04
          - env-ubuntu:24.04
          - env-ubuntu:latest
          - env-ubuntu:nolibs
          - toolchain-aarch64-linux-gnu
          - toolchain-arm-bcm2708hardfp-linux-gnueabi
          - toolchain-arm-linux-gnueabihf
          - toolchain-linux-android

    name: ${{ matrix.image }}

    env:
      CACHE_FROM: /tmp/.buildx-cache
      CACHE_TO: /tmp/.buildx-cache-new

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup cache
        uses: actions/cache@v4.0.2
        with:
          path: ${{ env.CACHE_FROM }}
          key: ${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.image }}-

      - name: Setup buildx
        run: |
          docker buildx create --use

      - name: Setup env
        if: |
          github.repository_owner == 'jevinskie' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/jevinskie/main'
        run: |
          echo "ENABLE_PUSH=1" >> $GITHUB_ENV

      - name: Run docker
        run: |
          if [[ $ENABLE_PUSH = 1 ]]; then \
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            ./make.sh --push ${{ matrix.image }}
          else
            ./make.sh ${{ matrix.image }}
          fi

      - name: Move cache
        if: always()
        run: |
          rm -rf ${CACHE_FROM}
          mv ${CACHE_TO} ${CACHE_FROM}

      - name: Save cache
        uses: actions/cache/save@v4.0.2
        if: always()
        with:
          path: ${{ env.CACHE_FROM }}
          key: ${{ matrix.image }}-${{ github.sha }}
